import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavMenu from "./components/ui/NavMenu";
// import { MapProvider } from "@/app/providers/MapProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Himalayan Connect NYC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* navigation menu on header with improved styling */}
        <header className="bg-slate-100 text-black p-2 text-center fixed top-0 w-full z-50 h-[50px] shadow-md">
          <NavMenu />
        </header>
        <main className="mt-[100px]">{children}</main>
        {/* footer with improved styling */}
        <footer className="bg-slate-900 text-white p-4 text-center shadow-md">
          Himalayan Connect NYC
        </footer>
      </body>
    </html>
  );
}
