# name of workflow
name: Run Playwright Tests

# event that triggers the workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # validate:
  #   # the docker image that is used (a virtual Ubuntu machine)
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the code from the repository
  #     - uses: actions/checkout@v2
  #       # runs a node script to validate the json file
  #     - name: Validate Commands JSON structure
  #       run:
  #         node ./internal/validate-commands-json.js # e.g.

  #         # runs a node script to validate the commands
  #     - name: Validate Commands
  #       run: node ./internal/validate-commands.js

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test
